# Generated by Django 5.2.9 on 2025-12-29 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField(choices=[('Construction', 'Construction'), ('Software', 'Software'), ('Event', 'Event'), ('Other', 'Other')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_tickets', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('job_role', models.TextField(blank=True, null=True)),
                ('role', models.TextField(choices=[('Admin', 'Admin'), ('Member', 'Member')])),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending')),
                ('user_status', models.TextField(choices=[('active', 'Active'), ('busy', 'Busy'), ('offline', 'Offline')], default='active')),
                ('token', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('job_role', models.TextField(blank=True, null=True)),
                ('role', models.TextField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member')])),
                ('user_status', models.TextField(choices=[('active', 'Active'), ('busy', 'Busy'), ('offline', 'Offline')], default='active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
