# Generated by Django 5.2.9 on 2026-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_comment_out_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
