# Generated by Django 5.2.9 on 2026-02-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_plan_type'),
        ('workspaces', '0004_workspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization'),
        ),
    ]
