# Generated by Django 5.2.9 on 2026-03-04 05:07

import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='enabled_modules',
            field=models.JSONField(default=workspaces.models.default_modules),
        ),
    ]
