# Generated by Django 5.2.9 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_add_enabled_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.TextField(choices=[('Construction', 'Construction'), ('Software', 'Software'), ('Event', 'Event'), ('Other', 'Other')], db_index=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.TextField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Member', 'Member')], db_index=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user_status',
            field=models.TextField(choices=[('active', 'Active'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='active'),
        ),
    ]
