# Generated by Django 4.2.29 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_alter_workspace_status_alter_workspace_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='user_status',
            field=models.TextField(choices=[('active', 'Active'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='active'),
        ),
        migrations.AlterField(
            model_name='workspacesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
