# Generated by Django 5.2.12 on 2026-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_workspace_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
