# Generated by Django 5.2.9 on 2026-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidocument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki_covers/'),
        ),
    ]
