# Generated by Django 5.2.9 on 2026-03-08 15:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikidocument_image'),
        ('workspaces', '0007_alter_workspace_status_alter_workspace_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidocument',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='wikidocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wiki_wikido_search__2ef770_gin'),
        ),
    ]
