# Generated by Django 4.2.29 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikidocument_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
