# Generated by Django 5.2.9 on 2026-01-16 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_modules', models.JSONField(default=list)),
                ('module_order', models.JSONField(default=list)),
                ('quick_access_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('tasks', 'Tasks'), ('team', 'Team'), ('wiki', 'Wiki'), ('integrations', 'Integrations'), ('logs', 'Logs'), ('reports', 'Reports'), ('modules', 'Modules')], max_length=50)),
                ('session_duration', models.PositiveIntegerField(default=0)),
                ('actions_performed', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'module_name', 'accessed_at'], name='modules_mod_user_id_1f8e09_idx'), models.Index(fields=['workspace', 'module_name', 'accessed_at'], name='modules_mod_workspa_a3b196_idx'), models.Index(fields=['module_name', 'accessed_at'], name='modules_mod_module__83666a_idx'), models.Index(fields=['accessed_at'], name='modules_mod_accesse_d408dd_idx')],
            },
        ),
    ]
