# Generated by Django 5.2.9 on 2026-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Starter Organization'), ('pro', 'Pro Organization'), ('business', 'Business Organization'), ('enterprise', 'Enterprise Organization')], default='free', max_length=20),
        ),
    ]
