# Generated by Django 5.2.12 on 2026-03-10 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0008_alter_workspace_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('task_summary', 'Task Summary'), ('user_performance', 'User Performance'), ('workspace_overview', 'Workspace Overview'), ('time_tracking', 'Time Tracking'), ('milestone_progress', 'Milestone Progress'), ('sprint_report', 'Sprint Report'), ('personal_performance', 'Personal Performance'), ('task_history', 'Task History'), ('time_summary', 'Time Summary'), ('achievement_report', 'Achievement Report')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='json', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('file_url', models.URLField(blank=True)),
                ('job_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('task_summary', 'Task Summary'), ('user_performance', 'User Performance'), ('workspace_overview', 'Workspace Overview'), ('time_tracking', 'Time Tracking'), ('milestone_progress', 'Milestone Progress'), ('sprint_report', 'Sprint Report'), ('personal_performance', 'Personal Performance'), ('task_history', 'Task History'), ('time_summary', 'Time Summary'), ('achievement_report', 'Achievement Report')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__11a031_idx'), models.Index(fields=['category', 'is_active'], name='reports_rep_categor_caea25_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('task_summary', 'Task Summary'), ('user_performance', 'User Performance'), ('workspace_overview', 'Workspace Overview'), ('time_tracking', 'Time Tracking'), ('milestone_progress', 'Milestone Progress'), ('sprint_report', 'Sprint Report'), ('personal_performance', 'Personal Performance'), ('task_history', 'Task History'), ('time_summary', 'Time Summary'), ('achievement_report', 'Achievement Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=dict)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='SharedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.JSONField(default=list)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('download', 'Download')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('share_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='reports.report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workspace', 'report_type', 'created_at'], name='reports_rep_workspa_d313dc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'report_type', 'created_at'], name='reports_rep_user_id_2d6b64_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['job_id'], name='reports_rep_job_id_4b74e3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['workspace', 'is_active', 'next_run'], name='reports_sch_workspa_7d19a6_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['frequency', 'is_active', 'next_run'], name='reports_sch_frequen_b90d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedreport',
            index=models.Index(fields=['share_token'], name='reports_sha_share_t_d934a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedreport',
            index=models.Index(fields=['report', 'expires_at'], name='reports_sha_report__0d29d5_idx'),
        ),
    ]
