# Generated by Django 5.2.9 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_personaltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
