# Generated by Django 5.2.9 on 2026-03-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
