# Generated by Django 4.2.29 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
