# Generated by Django 5.2.9 on 2026-02-14 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organization_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('plan_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('free', 'Starter Plan'), ('pro', 'Pro Plan'), ('business', 'Business Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_provider', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20, null=True)),
                ('subscription_code', models.CharField(blank=True, help_text='Subscription code from payment provider', max_length=100, null=True)),
                ('email_token', models.CharField(blank=True, help_text='Email token for managing subscription', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
        ),
    ]
