# Generated by Django 5.2.9 on 2026-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='End of grace period after subscription expiry', null=True),
        ),
    ]
