# Generated by Django 5.2.9 on 2026-02-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_grace_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='authorization_code',
            field=models.CharField(blank=True, help_text='Token for recurring charges', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='If True, subscription cancels after end_date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_in_grace_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_charged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_plan_type',
            field=models.CharField(blank=True, choices=[('free', 'Starter Plan'), ('pro', 'Pro Plan'), ('business', 'Business Plan'), ('enterprise', 'Enterprise Plan')], help_text='Plan to switch to after end_date', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_retry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
