# Generated by Django 5.2.9 on 2026-03-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_paymenthistory_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Email used from the payment gateway associated with the token', max_length=254, null=True),
        ),
    ]
