# Generated by Django 5.2.9 on 2026-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_expiry',
            field=models.CharField(blank=True, help_text='Card expiry e.g. 09/32', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_first6',
            field=models.CharField(blank=True, help_text='First 6 digits (BIN) of the card', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the card', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_type',
            field=models.CharField(blank=True, help_text='Card brand e.g. VISA, MASTERCARD', max_length=20, null=True),
        ),
    ]
