# Generated by Django 5.2.9 on 2026-03-01 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_plan_type'),
        ('subscriptions', '0006_subscription_card_expiry_subscription_card_first6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('card_last4', models.CharField(help_text='Last 4 digits of the card', max_length=4)),
                ('card_type', models.CharField(blank=True, default='', help_text='Card brand e.g. VISA, MASTERCARD', max_length=20)),
                ('card_expiry', models.CharField(blank=True, default='', help_text='Card expiry e.g. 09/32', max_length=7)),
                ('card_first6', models.CharField(blank=True, default='', help_text='First 6 digits (BIN)', max_length=6)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'provider', 'card_last4')},
            },
        ),
    ]
