# Generated by Django 5.2.9 on 2026-03-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_first6',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_type',
        ),
    ]
