# Generated by Django 5.2.12 on 2026-03-10 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('acknowledged', 'Acknowledged')], db_index=True, default='active', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'status', 'created_at'], name='monitoring__severit_ed6ffe_idx'), models.Index(fields=['alert_type', 'status'], name='monitoring__alert_t_296853_idx'), models.Index(fields=['status', 'created_at'], name='monitoring__status_1c9c1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('performance', 'Performance'), ('usage', 'Usage'), ('error', 'Error'), ('security', 'Security')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='monitoring__metric__a40156_idx'), models.Index(fields=['metric_name', 'timestamp'], name='monitoring__metric__3f2f80_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_5031bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('metadata', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'metric_name', 'date'], name='monitoring__organiz_6d3f85_idx'), models.Index(fields=['organization', 'date'], name='monitoring__organiz_667d07_idx'), models.Index(fields=['date'], name='monitoring__date_1d4bfe_idx')],
                'unique_together': {('organization', 'metric_name', 'date')},
            },
        ),
    ]
