# Generated by Django 5.2.9 on 2026-01-16 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_workspace_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite_modules', models.JSONField(default=list)),
                ('module_order', models.JSONField(default=list)),
                ('quick_access_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'action', 'created_at'], name='logs_auditt_workspa_9a170a_idx'), models.Index(fields=['user', 'created_at'], name='logs_auditt_user_id_5f02fd_idx'), models.Index(fields=['entity_type', 'entity_id'], name='logs_auditt_entity__2d5750_idx'), models.Index(fields=['created_at'], name='logs_auditt_created_c4bfa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(choices=[('dashboard', 'Dashboard'), ('tasks', 'Tasks'), ('team', 'Team'), ('wiki', 'Wiki'), ('integrations', 'Integrations'), ('logs', 'Logs'), ('reports', 'Reports'), ('modules', 'Modules')], max_length=50)),
                ('session_duration', models.PositiveIntegerField(default=0)),
                ('actions_performed', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'module_name', 'accessed_at'], name='logs_module_user_id_1ab637_idx'), models.Index(fields=['workspace', 'module_name', 'accessed_at'], name='logs_module_workspa_1f9b0d_idx'), models.Index(fields=['module_name', 'accessed_at'], name='logs_module_module__1f556e_idx'), models.Index(fields=['accessed_at'], name='logs_module_accesse_7afe2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('security', 'Security'), ('performance', 'Performance')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('stack_trace', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'event_type', 'created_at'], name='logs_system_workspa_33d807_idx'), models.Index(fields=['severity', 'resolved', 'created_at'], name='logs_system_severit_78593d_idx'), models.Index(fields=['event_type', 'severity'], name='logs_system_event_t_cdb120_idx'), models.Index(fields=['created_at'], name='logs_system_created_5169e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('page_view', 'Page View'), ('api_call', 'API Call'), ('file_download', 'File Download'), ('search', 'Search'), ('export', 'Export')], max_length=50)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'workspace', 'created_at'], name='logs_userac_user_id_6bf3b8_idx'), models.Index(fields=['activity_type', 'created_at'], name='logs_userac_activit_8ff6e6_idx'), models.Index(fields=['session_id', 'created_at'], name='logs_userac_session_c67eed_idx'), models.Index(fields=['created_at'], name='logs_userac_created_c3599d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('task_create', 'Task Created'), ('task_update', 'Task Updated'), ('task_status_change', 'Task Status Changed'), ('task_delete', 'Task Deleted'), ('comment_create', 'Comment Created'), ('comment_update', 'Comment Updated'), ('comment_delete', 'Comment Deleted'), ('team_update', 'Team Updated'), ('wiki_create', 'Wiki Created'), ('wiki_update', 'Wiki Updated'), ('wiki_delete', 'Wiki Deleted'), ('integration_create', 'Integration Created'), ('integration_update', 'Integration Updated'), ('integration_delete', 'Integration Deleted'), ('workspace_update', 'Workspace Updated'), ('member_add', 'Member Added'), ('member_remove', 'Member Removed'), ('file_upload', 'File Uploaded'), ('backup_create', 'Backup Created'), ('settings_update', 'Settings Updated')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'log_type', 'created_at'], name='logs_worksp_workspa_1335e9_idx'), models.Index(fields=['user', 'created_at'], name='logs_worksp_user_id_0afeb9_idx'), models.Index(fields=['severity', 'created_at'], name='logs_worksp_severit_c2a5e3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='logs_worksp_entity__407f8c_idx'), models.Index(fields=['created_at'], name='logs_worksp_created_4aba1a_idx')],
            },
        ),
    ]
