# Generated by Django 5.2.9 on 2026-02-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulepreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModuleAccess',
        ),
        migrations.DeleteModel(
            name='ModulePreferences',
        ),
    ]
