# Generated by Django 5.2.9 on 2026-03-08 15:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_modulepreferences_user_delete_moduleaccess_and_more'),
        ('workspaces', '0007_alter_workspace_status_alter_workspace_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacelog',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='workspacelog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='logs_worksp_search__e0449c_gin'),
        ),
    ]
