# Generated by Django 4.2.29 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_workspacelog_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittraillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='systemeventlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workspacelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
