# Generated by Django 5.2.12 on 2026-04-17 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0007_alter_task_end_date_alter_task_start_date'),
        ('workspaces', '0008_alter_workspace_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment', models.CharField(choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('BAD', 'Bad'), ('TERRIBLE', 'Terrible')], default='GOOD', max_length=10)),
                ('yesterday_progress', models.TextField(blank=True, default='')),
                ('tomorrow_plan', models.TextField(blank=True, default='')),
                ('has_blockers', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tomorrow_tasks', models.ManyToManyField(blank=True, related_name='checkin_tomorrow', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='workspaces.workspace')),
                ('yesterday_tasks', models.ManyToManyField(blank=True, related_name='checkin_yesterday', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CheckInBlocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocker_mentions', to=settings.AUTH_USER_MODEL)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='checkins.dailycheckin')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
