# Generated by Django 5.2.12 on 2026-04-17 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
        ('tasks', '0007_alter_task_end_date_alter_task_start_date'),
        ('workspaces', '0008_alter_workspace_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['workspace', 'date'], name='checkins_da_workspa_da0afc_idx'),
        ),
    ]
