# Generated by Django 5.2.12 on 2026-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_dailycheckin_checkins_da_workspa_da0afc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='sentiment',
            field=models.CharField(choices=[('CRUSHING', 'Crushing'), ('GOOD', 'Good'), ('OKAY', 'Okay'), ('LOW', 'Low')], default='GOOD', max_length=10),
        ),
    ]
