# Generated by Django 4.2.29 on 2026-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_func', '0005_customuser_bio_customuser_phone_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], db_index=True, default='active', max_length=20),
        ),
    ]
