# Generated by Django 5.2.12 on 2026-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_func', '0006_alter_customuser_created_at_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_workspace',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
